# Transceivers {-}

Actually, covering both transceivers and receivers I have.

## Transceivers {-}

Currently, I have a [Xiegu G90](https://xiegu.eu/product/xiegu-g90-hf-20w-sdr-transceiver/)
for HF, and a
[Baofeng UV5RIII](http://www.baofengradio.co.uk/uv-5r-iii-tri-band-green-camouflage-vhf136-174mhz-220-260mhz-uhf-400-520mhz-walkie-talkie-long-range-two-way-fm-radio-speaker-mic-usb-cable/)
for VHF/UHF.

## Receivers {-}

I have a few SDRs of differing capabilities I used for learning my way around the bands and generally
getting a feel for what was achievable at my QTH. These include:

- A very cheap ['RTL SDR' dongle](https://www.rtl-sdr.com/about-rtl-sdr/) with a Fitipower tuner.
  It's pretty junk. I spent some effort improving it (shielding etc.). It still won't pick much
  up outside of commercial broadcast stations (including DAB and DVB). I'd probably recommend nobody
  purchases one of these unless they know what they are getting and going to do with it, and instead
  go for the below `RTL-SDR BLOG V3` improved version instead.
- An [RTL-SDR BLOG V3 dongle](https://www.rtl-sdr.com/about-rtl-sdr/), with VHF/UHF wideband LNA.
  This is a good step up in performance from the basic cheap dongles - better filtering, s/n ratio
  and features, including the ability to 'direct sample' HF frequencies.
- An [Airspy HF+](https://airspy.com/airspy-hf-plus/). Which is a large leap up in performance again.
  The frequency range and rate (width) is limited, but not to a point where it stops you looking at
  useful ranges - but the performance is much better - with some very smart adaptive techniques
  and sample bit depth. I'm happy to recommend the Airspy. Do do some research and read into how it
  works internally and check the frequency range and bandwidth limitations are not going to be an
  issue for you though. If you wanted more bandwidth, the [SDRplay](https://www.sdrplay.com/) units
  look good - and having one of those is somewhere down my 'want' list.
