# Copyright (c) 2020 Graham Whaley
#
# SPDX-License-Identifier: Apache-2.0

# Docker 'verse' comes with the publishing tools...
FROM rocker/verse

LABEL DOCKERFILE_VERSION="1.0"

ENV DEBIAN_FRONTEND=noninteractive

